export const PLAYER_INIT = 'PLAYER_INIT';
export const PLAYER_ADD = 'PLAYER_ADD';
export const PLAYER_DELETE = 'PLAYER_REMOVE';
export const PLAYER_UPDATE = 'PLAYER_UPDATE';

export const PLAYER_ASSIGN_TEAM = 'PLAYER_ASSIGN_TEAM';

export const PLAYER_FORM_OPEN = 'PLAYER_FORM_OPEN';
export const PLAYER_FORM_CLOSE = 'PLAYER_FORM_CLOSE';


